### ISSUE TITLE
v1.1.0 Require-Spec

### ISSUE THREAD

**Issue by jyeonjyan** [themoment-team/the_moment_server#173]
### 아래와 같은 스펙을 v1.1.0 에서 요구합니다
1. 이모지 추가 가능 (DB 설정 및 SpringApplication 설정 변경)
2. JPQL -> Querydsl 로 마이그레이션 
3. 좋아요 2주에 한번씩 모두 refresh 처리 혹은 그에 준하는 방법으로 개선

**Comment by siwony** [comment]
확인했습니다.

**Comment by jyeonjyan** [comment]
v1.1.0 에는 gradle 마이그레이션 분기 merge 진행합니다.
---------------------------------------------------
일정은 아래와 같습니다.
v1.1.0 : gradle 마이그레이션
v1.1.1 : [현]기능 코드 리팩터링
v1.1.2 : jpql -> querydsl +a
