### ISSUE TITLE
v1.2.1 마이그레이션 업무 중 유의사항

### ISSUE THREAD

**Issue by jyeonjyan** [themoment-team/the_moment_server#191]
![image](https://user-images.githubusercontent.com/67095821/132154039-a050bcbf-9127-4693-b119-a8a9890618a3.png)

여기 보면 `UncomfortableEntity table` 로 아직 `table` 이 별칭으로 돼 있는데..
어차피 querydsl로 v1.2.2 에서 반영, 교체 될 것 이기에, 현 시점 v1.1.0 기준으로는 JPQL 의 세부 스팩까지 수정할 필요가 없을 것 같습니다.

**Comment by siwony** [comment]
UncomfortableEntity의 boardIdx 변수를 uncomfortableIdx로 이름 변경하려 하는데 그러면 어쩔 수 없이 변경해야 하네요 ㅜㅜ...
