### ISSUE TITLE
v1.1.1 bug - join, login | 치명적인 bug

### ISSUE THREAD

**Issue by jyeonjyan** [themoment-team/the_moment_server#208]
### 문제상황
localhost test(8080)은 정상적인 결과를 반환하지만, docker-compose test는 요청에 부적절한 결과를 반환한다.

### 참고사항
1. localhost test - http://localhost:8080/v1/join
![image](https://user-images.githubusercontent.com/67095821/134798149-8238a979-78a2-4758-bc4b-bde50f4906e5.png)

2. docker-compose test - http://localhost:5000/v1/join
![image](https://user-images.githubusercontent.com/67095821/134798205-a2223c64-2071-4692-8371-84d42944492f.png)

- response 와 다르게 정작 console에는 200을 반환함
![image](https://user-images.githubusercontent.com/67095821/134798225-5adf078b-2dba-43ed-8453-f5c3a1b1e92e.png)

**Comment by siwony** [comment]
실험을 해보니 logging이 잘못된 http status를 반환하고 있었네요 해당 기능을 fix후 pr 날리겠습니다. (혹은 제거)

+ 해당 /v1/join API에 대한 원인을 찾아보도록 하겠습니다

**Comment by siwony** [comment]
#### develop branch 기준으로 docker-compose의 API변경사항이 적용되지 않은 거 같습니다.
회원가입 API의 주소가 `/v1/signup`에서 `/v1/join`으로 변경되고 request body도 변경이 되었지만 이전API를 사용했더니 성공했습니다.
다음 img는 제가 local에서 postman으로 요청한 사진입니다.
![image](https://user-images.githubusercontent.com/62932968/134829551-2496d0e4-e3d9-43e8-8456-1069c615b3a3.png)

login API 마찬가지로 `400 - Bad request`를 반환하지 않네요 하지만, redis와 connect가 실패했네요
![image](https://user-images.githubusercontent.com/62932968/134829702-3f4b0370-3bf1-4717-af6c-8cd7b443d398.png)

#### hotfix branch를 marge한 후 master기준으로 실험을 해보니 정상작동 합니다.
![image](https://user-images.githubusercontent.com/62932968/134830322-e50be07d-bfaa-4461-a049-
b81d1814f258.png)
![image](https://user-images.githubusercontent.com/62932968/134830354-c5eca962-975b-4798-80f1-c74c098cb427.png)

**Comment by jyeonjyan** [comment]
네 이 부분은 어제 디스코드 에서 언급한 부분입니다..
현재 app.yml 이 운영기준으로 redis 설정이 돼 있어서 localhost-test 에서는 redis unable to connect 일겁니다.

그리고 어제 모든 pr 은 hotfix to master 로 했기에 develop 상태는 legacy 가 당연합니다.
